### ISSUE TITLE
Formatting of release notes for TestFlight (and non-markdown destinations)

### ISSUE THREAD

**Issue by jonlay** [xotahal/fastlane-plugin-semantic_release#13]
Appreciating your plugin a lot, at present!

One thing we have noticed is that the `markdown`/`slack` formatting options aren't ideal when a changelog is being produced for internal TestFlight releases, because Markdown isn't supported in that location:

![image](https://user-images.githubusercontent.com/1898889/67279682-67df5380-f4c3-11e9-9e61-619e115be577.png)

Would you have any suggestions (or objections) for creating a `self.plaintext` inside `ConventionalChangelogAction`? I see there is quite a lot of code duplication between `slack` and `markdown` so I wouldn't want to further complicate this, but creating that additional option would be helpful for our purposes.

Ruby is not my main language but I might also look at creating a customisable `exclude` parameter so that changelog commits tagged as `ci`, `docs` etc do not show up in release notes.

I won't have time to jump into this right away, but would be useful if you have any comments, and I'll see if I get a chance to make some tweaks 😄

**Comment by jonlay** [comment]
Hey Jiří!

Are you actively maintaining/accepting changes to this plugin?

I'd rather make contributions to this repository and have them merged into master, to contribute to the community, but if you are abandoning the plugin, I guess I will fork it for my own purposes.

I've also submitted a PR over here for a different tweak: https://github.com/xotahal/fastlane-plugin-semantic_release/pull/12

**Comment by jonlay** [comment]
Hey there - I've pushed ahead and forked the repository and have started to make some improvements here: https://github.com/jonlay/fastlane-plugin-semantic_release/commits/develop

It's definitely not my _preference_ to fork the repository and deal with new project setup on npm - I'm going to hold off doing that for a while.

Hoping you are still up for accepting contributions, but I'm going to assume that this is a dead project otherwise.

Let me know if the project is still alive! 😄

**Comment by xotahal** [comment]
Hey mate! Sorry about being unresponsive. We all have our own lives, right :) Yeah the project is still alive and I accept pull requests (as I've already done with the one you made).

You can exclude a section by setting up the `order` param. Just skip the section you want to exclude. Is that what you're trying to achieve?

And yeah, plain text is definitely something we could support!

This is my very first contact with Ruby language as well :D So I believe the code is not ideal, but it does the work I need it to do.

**Comment by jonlay** [comment]
Totally! Just glad to hear that you are still OK to have contributions 🙌 

I'll have a think about the `order` situation. I think it might make more sense to instead create an `exclude_sections` parameter. But can do that later.

I think I have a nice solution for plain text format - I'll open up a (big) PR and we can discuss over there 😄

**Comment by xotahal** [comment]
Agree, it could be called maybe `sections` instead of `order` but I don't think we need to introduce a new parameter.

**Comment by jonlay** [comment]
👍 renaming `order` to `sections` could work quite nicely.

I might have a try at that at some point - not the highest on my personal list, but would be a clearer enhancement I suppose 😄

**Comment by xotahal** [comment]
Just thinking if we need to do "Breaking Change" just because we don't really like the naming. Maybe we could wait till we have more breaking changes. This is not a really big issue.

**Comment by xotahal** [comment]
Plain text available in version 1.5.1

**Comment by jonlay** [comment]
👍
