### ISSUE TITLE
Follow Conventional Commits spec

### ISSUE THREAD

**Issue by cedricfressin** [xotahal/fastlane-plugin-semantic_release#2]
Even if the plugin is pretty cool it's not following completely the convention spec: 
- every Git message with a `scope` is not considered
- `BREAKING CHANGES:` are not detected

Suggestion : change the way message are analysed in [analyze_commits.rb](https://github.com/xotahal/fastlane-plugin-semantic_release/blob/master/lib/fastlane/plugin/semantic_release/actions/analyze_commits.rb). Probably with regex…

**Comment by xotahal** [comment]
This is more like a beta version (should've been marked correctly). I wrote the plugin just for myself actually. But yeah, I already run into these problems.

So agree, let's do that. Can you do PR?

**Comment by xotahal** [comment]
Fix code to follow the specification in analyze_commits

- works with scopes and breaking change

https://github.com/xotahal/fastlane-plugin-semantic_release/releases/tag/v1.0.10
