### ISSUE TITLE
Question: recommended way of attaching changelog to git tag?

### ISSUE THREAD

**Issue by aecorredor** [xotahal/fastlane-plugin-semantic_release#20]
I'm wondering what's the best way to attach the release notes generated by `conventional_changelog` to the git tag that I create and push to my repository when a deployment is successful. I saw that the `add_git_tag` command takes a `message` paramater, but then it says that if you use the `tag` parameter, all others are ignored. In my case, I'm using `tag`, so I don't think passing the changelog to the `message` option will work. 

Has anybody found an efficient way to do this? I don't want to have to copy/paste the changelog from slack into GitHub manually every time.

**Comment by marcelojunior7** [comment]
Maybe you can use [set_github_release](https://docs.fastlane.tools/actions/set_github_release/) sending your `tag_name` created and a `description` with your last changelog

**Comment by aecorredor** [comment]
Yeap! that's actually what I ended up doing. Forgot to close this. Thanks @marcelojunior7
