### ISSUE TITLE
Option to override defaults

### ISSUE THREAD

**Issue by schilumula** [xotahal/fastlane-plugin-semantic_release#22]
Currently this is following, conventional changelog. We want the script to check for other format of commits to trigger the build. Can you provide an option to override the defaults.

**Comment by xotahal** [comment]
What defaults? You mean [this](https://github.com/xotahal/fastlane-plugin-semantic_release/blob/e02da33d664921527713869f7d84ee3bf9e199fc/lib/fastlane/plugin/semantic_release/actions/analyze_commits.rb#L231)

**Comment by schilumula** [comment]
https://github.com/xotahal/fastlane-plugin-semantic_release/blob/e02da33d664921527713869f7d84ee3bf9e199fc/lib/fastlane/plugin/semantic_release/helper/semantic_release_helper.rb#L21-L25

If we can override this pattern and use our own custom pattern to determine major, minor or patch, that would be helpful

**Comment by sudheerchilumula** [comment]
Thank you.
