### ISSUE TITLE
undefined method `match' for nil:NilClass

### ISSUE THREAD

**Issue by johanquiroga** [xotahal/fastlane-plugin-semantic_release#4]
I upgraded from 1.0.8 to 1.1.0 and received the following error from `analyze_commits` action:

![Image 2019-05-29 at 5 42 07 PM](https://user-images.githubusercontent.com/22845267/58596346-4c845b00-8239-11e9-99e8-193791707b90.png)

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.123.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                           | Version | Update-Status |
| -------------------------------- | ------- | ------------- |
| fastlane-plugin-semantic_release | 1.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                              | Version      |
| -------------------------------- | ------------ |
| did_you_mean                     | 1.3.0        |
| bundler                          | 2.0.1        |
| CFPropertyList                   | 3.0.0        |
| public_suffix                    | 2.0.5        |
| addressable                      | 2.6.0        |
| atomos                           | 0.1.3        |
| babosa                           | 1.0.2        |
| claide                           | 1.0.2        |
| colored                          | 1.2          |
| colored2                         | 3.1.2        |
| highline                         | 1.7.10       |
| commander-fastlane               | 4.4.6        |
| declarative                      | 0.0.10       |
| declarative-option               | 0.1.0        |
| digest-crc                       | 0.4.1        |
| unf_ext                          | 0.0.7.6      |
| unf                              | 0.1.4        |
| domain_name                      | 0.5.20180417 |
| dotenv                           | 2.7.2        |
| emoji_regex                      | 1.0.1        |
| excon                            | 0.64.0       |
| multipart-post                   | 2.0.0        |
| faraday                          | 0.15.4       |
| http-cookie                      | 1.0.3        |
| faraday-cookie_jar               | 0.0.6        |
| faraday_middleware               | 0.13.1       |
| fastimage                        | 2.1.5        |
| gh_inspector                     | 1.1.3        |
| jwt                              | 2.2.1        |
| memoist                          | 0.16.0       |
| multi_json                       | 1.13.1       |
| os                               | 1.0.1        |
| signet                           | 0.11.0       |
| googleauth                       | 0.6.7        |
| httpclient                       | 2.8.3        |
| mime-types-data                  | 3.2019.0331  |
| mime-types                       | 3.2.2        |
| uber                             | 0.1.0        |
| representable                    | 3.0.4        |
| retriable                        | 3.1.2        |
| google-api-client                | 0.23.9       |
| google-cloud-env                 | 1.0.5        |
| google-cloud-core                | 1.3.0        |
| google-cloud-storage             | 1.16.0       |
| json                             | 2.2.0        |
| mini_magick                      | 4.5.1        |
| multi_xml                        | 0.6.0        |
| plist                            | 3.5.0        |
| rubyzip                          | 1.2.3        |
| security                         | 0.1.3        |
| naturally                        | 2.2.0        |
| simctl                           | 1.6.5        |
| slack-notifier                   | 2.3.2        |
| terminal-notifier                | 2.0.0        |
| unicode-display_width            | 1.6.0        |
| terminal-table                   | 1.8.0        |
| tty-screen                       | 0.7.0        |
| tty-cursor                       | 0.6.1        |
| tty-spinner                      | 0.9.0        |
| word_wrap                        | 1.0.0        |
| nanaimo                          | 0.2.6        |
| xcodeproj                        | 1.9.0        |
| rouge                            | 2.0.7        |
| xcpretty                         | 0.3.0        |
| xcpretty-travis-formatter        | 1.0.0        |
| fastlane-plugin-semantic_release | 1.1.0        |
</details>

*generated on:* **2019-05-29**
</details>

**Comment by xotahal** [comment]
Know about it, happened to me today as well ... Hopefully, I will fix it today or tomorrow ...

**Comment by xotahal** [comment]
Fix in version > 1.1.2
