### ISSUE TITLE
Replace `#` prefix for conventional changelog title

### ISSUE THREAD

**Issue by karlmarxlopez** [xotahal/fastlane-plugin-semantic_release#6]
Hi, thanks for this awesome plugin! I have a minor issue on Gitlab, the `#` prefix before version is mentioning issues. I checked the code and the pound sign is hard coded, would it be better if this is configurable via params? Or just make it a header on markdown e.g `# My title`

**Comment by xotahal** [comment]
Do you mean this? https://github.com/xotahal/fastlane-plugin-semantic_release/blob/master/lib/fastlane/plugin/semantic_release/actions/conventional_changelog.rb#L48

It is a markdown. Not sure if I understand the problem ...

**Comment by karlmarxlopez** [comment]
Nope, I think this is the line, https://github.com/xotahal/fastlane-plugin-semantic_release/blob/0638d85945fc42031e2f19fba963f4d54458cc9c/lib/fastlane/plugin/semantic_release/actions/conventional_changelog.rb#L51

**Comment by xotahal** [comment]
That will produce:

```
#Title (date)
```

There should be space, hmm? Do you mean this? Could you open the PR?

Should be like this:

```
# Title (date)
```
