### ISSUE TITLE
Ignore commits with specific string

### ISSUE THREAD

**Issue by aecorredor** [xotahal/fastlane-plugin-semantic_release#7]
I have a react native app inside a lerna monorepo where all packages use semantic release. I only want to release if my native package has changed. I have commits that are like feat(native), feat(server), feat(web), and I'd like to ignore commits with web and server when deploying native. 

My problem is that if I use conventional commits for other packages other than native, native will also recognize those and bump the version, causing an unnecessary release trigger. The only option I see right now is to only use conventional commits for my native package.

One thing I thought of was maybe adding a feature to the plugin that allows us to pass a `scope` to `analyze_commits` and `conventional_changelog` so the scripts only look at commits with that scope.

What do you guys think?

I can maybe give it a go if I get some guidance.

**Comment by jonlay** [comment]
@xotahal I had a go at this over the weekend (locally) - was pretty simple to get it working on the `analyze_commits` action (I even did some refactoring of the tests while I was at it).

Is this something you'd consider merging if I drafted a PR at some point in the next week or two?

**Comment by aecorredor** [comment]
@jonlay that'd be awesome! how would it work? Would the `analyze_commits` action take an extra parameter?

**Comment by jonlay** [comment]
Yeah, it's just `ignore_scopes: ['android','windows']`.

Would also need to be replicated in the `conventional_changelog` action, however, as the ignored scoped commits would otherwise still show up in the changelog, even if they didn't allow a build to be triggered.

Not produced a PR for this yet, but working fine on the `analyze_commits` action in initial tests.

https://github.com/jonlay/fastlane-plugin-semantic_release/commits/ignore-scopes

**Comment by aecorredor** [comment]
It's looking good man @jonlay! thanks for this. Let's see what @xotahal thinks about it.

**Comment by xotahal** [comment]
@jonlay  Can you create the PR, please? 🙏

**Comment by jonlay** [comment]
Yeah, will do soon.

I wasn't happy about needing to pass `ignore_scopes: ['android','windows']` to the `conventional_changelog` action as well as the `analyze_commits` one, so I was having a bit of a think about an improved way to structure that.

Didn't want to ship this feature, then end up refactoring it again right after! 🤷‍♂

**Comment by aecorredor** [comment]
@jonlay let me know if you need help reviewing or knocking something out to get this in 🎉

**Comment by jonlay** [comment]
Sorry @aecorredor - this has been on my mind, but I'm totally overloaded at the moment.

I've put out the PR, so if you want to fork/review/build upon that one, I'm totally open to that. Better for someone else to take this forward than for it to languish in my private repo!

**Comment by aecorredor** [comment]
@jonlay no problem man! there's no rush. I'll start reviewing and if anything I can fork off it for now. Thanks a lot for this.

**Comment by xotahal** [comment]
PR Merged

**Comment by MiguelSOliveira** [comment]
Sorry guys from what I understood we still don't have a way to Ignore commits with specific string in the conventional_changelog action?
